### PR TITLE
typescript 4.3 support

### PR DESCRIPTION
**Pull request by BrianLeishman**
So I got tscc to work with TS 4.3 now that tsickle supports it, but there's gray areas that I'm not 100% about. 

First thing, it seems like tsickle has an issue installing on version 0.40.0 from npm where the package.json points to the wrong dir for its own files. I made an issue with them about that https://github.com/angular/tsickle/issues/1272. That's what the patch file in this commit does.

Second is with the `const sf = <SourceFileWithInternalAPIs>this.host.getSourceFile(fileName);` line. This seems to be related this issue https://github.com/theseanl/tscc/issues/464. In my own environment, I've jst been skipping the next actions if that line returns something falsey. I've not personally experienced any cons from that, but it feels like maybe not the right solution,

Lastly, with the `const transformerHost: tsickle.TsickleHost = {` line, it seems like this version of tsickle requires a new function as part of the `tsickle.TsickleHost` interface, called `rootDirsRelative` that takes a filename and returns a string. I couldn't find anything about what specifically this does, so I just wrote it to return what was passed to it and my compiled code seems to be working correctly, but again, not sure that's the right solution.

### CODE REVIEW

**Comment by BrianLeishman** [comment]
tsickle fixed the issue with the package.json file so it's all good to go now with tsickle version 0.41.0

**Comment by theseanl** [comment]
Much appreciated! I will try to wrap my head around the recent changes of tsickle and review it. It's disappointing that they haven't improved in terms of module-`.d.ts` support. 

I guess `CompilerHost.getSourceFile` returning nullish requires a bit of consideration. Regarding `rootDirsRelative`, I guess you are right, because as I remember, back then there were a lot of path-related issues with tsickle, and I just forced tscc to use absolute paths everywhere whenever possible.

**Comment by theseanl** [comment]
Hi, the change seemed mostly fine, I made a few quick change and squash-merged with the master (I didn't know that your account is not displayed in commit log if I do this).
 - Regarding the new requirement of `rootDir` compiler option
   - It is pointless in `tscc`, as tscc as been working just fine without `rootDir` option. Instead of commenting out some lines as you have did, I went to modify `rootFile` property to a some dummy path. It is set to a root path of a current config file's path. In case of linux, it will always be `/`, and in Windows, it will be something like `C:\\` .
  - Regarding `!sf` check: I can't make a reproduction case of what you have described, so removed this patch. Please file a new issue with steps to reproduce the issue.
  -  I also modified clarified some comments.

**Comment by BrianLeishman** [comment]
Yeah I figured the yarn/npm thing would come up. I learned about yarn vs npm over the last week or so, but before that I was struggling with the yarn side, and only npm was working for me, but of course it put it's package-lock file there. 

I'll see if I can get a reproducible build for the issue about those dependencies that seem to be missing causing issues with the `!sf` line/check

**Comment by theseanl** [comment]
Well, I just wanted to make sure I mention every change and its reason, what package manager to use is a very marginal issue I guess. While waiting for tsickle release, my attention was slowly slipping over to other tasks. Thank you for bring this up and providing & testing necessary changes! Also now tscc 0.7.0 with typescript 4.3.2 is live in NPM.

**Comment by BrianLeishman** [comment]
That's awesome, thank you!

**Pull request closed without merging**
